DEFAULT_PORT = 8563
DEFAULT_AUTOCOMMIT = True

DEFAULT_SOCKET_TIMEOUT = 10
DEFAULT_QUERY_TIMEOUT = 0

DEFAULT_FETCHMANY_SIZE = 10000

CLIENT_NAME = 'PyEXASOL'
DRIVER_NAME = 'PyEXASOL'

LOGGER_TIMESTAMP_FORMAT = '%Y-%m-%d %H:%M:%S.%f'
LOGGER_MAX_JSON_LENGTH = 10000
