name: Continues Integration (Master)

on:
  push:
    branches:
      - "master"
      - "main"
  schedule:
    # “At 00:00 on every 7th day-of-month from 1 through 31.” (https://crontab.guru)
    - cron: "0 0 1/7 * *"

jobs:
  verify:
    uses: ./.github/workflows/checks.yml

  examples:
    uses: ./.github/workflows/examples.yml

  ssl_cert:
    uses: ./.github/workflows/ssl_cert.yml
