name: Continuous Integration (Master)

on:
  push:
    branches:
      - "polars"

jobs:
  verify:
    uses: ./.github/workflows/checks.yml

  examples:
    uses: ./.github/workflows/examples.yml

  ssl_cert:
    uses: ./.github/workflows/ssl_cert.yml
