name: Examples

on:
  workflow_call:

jobs:
  build-matrix:
    name: Generate Build Matrix
    uses: ./.github/workflows/matrix.yml
    with:
      matrix_keys_json: '["exasol_versions"]'

  examples:
    name: Run Examples (Python-${{ matrix.python_versions }}, Exasol-${{ matrix.exasol_versions}})
    needs: [ build-matrix ]
    # For all containers with versions 7.1.x and older versions 8.y.z of docker-db,
    # there will be a crash if UDFs (User Defined Functions) are utilized.
    runs-on:  ubuntu-24.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python_versions: ["3.12"]
        exasol_versions: ${{ fromJson(needs.build-matrix.outputs.matrix).exasol_versions }}
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v9
        with:
          python-version: ${{ matrix.python_versions }}
          poetry-version: "2.3.0"
          extras: "all"

      - name: Fix VM Crash in UDFs
        id: fix-vm-crash
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Start test db
        run: poetry run -- nox -s db:start -- --db-version ${{ matrix.exasol_versions }}

      - name: Wait for Exasol container (UDF extraction)
        run: poetry run -- python examples/_wait_container.py

      - name: Run examples
        run: poetry run -- nox -s run:examples

      - name: Stop test db
        run: poetry run -- nox -s db:stop
