name: Periodic-Validation

on:
  schedule:
    # At 00:00 on Saturday. (https://crontab.guru)
    - cron: "0 0 * * 6"

jobs:
  run-fast-checks:
    name: Fast Checks
    uses: ./.github/workflows/checks.yml
    permissions:
      contents: read

  run-fast-tests:
    name: Fast Tests
    uses: ./.github/workflows/fast-tests.yml
    permissions:
      contents: read

  run-slow-checks:
    name: Slow Checks
    uses: ./.github/workflows/slow-checks.yml
    secrets: inherit
    permissions:
      contents: read

  report:
    name: Report
    needs:
      - run-fast-checks
      - run-fast-tests
      - run-slow-checks
    uses: ./.github/workflows/report.yml
    secrets: inherit
    permissions:
      contents: read
