name: PR-Merge

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:

  # This job can be removed if certain preconditions are met. See
  # https://exasol.github.io/python-toolbox/user_guide/workflows.html#pr-merge-workflow

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml
    permissions:
      contents: read

  publish-docs:
    name: Publish Documentation
    uses: ./.github/workflows/gh-pages.yml
    permissions:
      contents: read
      pages: write
      id-token: write

  metrics:
    needs: [ ci-job ]
    uses: ./.github/workflows/report.yml
    secrets: inherit
    permissions:
      contents: read
